version: '3.4'

services:
  dapr.samples.ui:
    image: ${DOCKER_REGISTRY-}daprsamplesui
    build:
      context: .
      dockerfile: Dapr.Samples.UI/Dockerfile

  dapr.samples.calculator.add:
    image: ${DOCKER_REGISTRY-}daprsamplescalculatoradd
    build:
      context: .
      dockerfile: Dapr.Samples.Calculator.Add/Dockerfile

  dapr.samples.calculator.subtract:
    image: ${DOCKER_REGISTRY-}daprsamplescalculatorsubtract
    build:
      context: .
      dockerfile: Dapr.Samples.Calculator.Subtract/Dockerfile


  dapr.samples.calculator.multiply:
    image: ${DOCKER_REGISTRY-}daprsamplescalculatormultiply
    build:
      context: .
      dockerfile: Dapr.Samples.Calculator.Multiply/Dockerfile


  dapr.samples.calculator.divide:
    image: ${DOCKER_REGISTRY-}daprsamplescalculatordivide
    build:
      context: .
      dockerfile: Dapr.Samples.Calculator.Divide/Dockerfile

